apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  SERVER_PORT: {{ .Values.config.serverPort | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.config.database.url | quote }}
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: {{ .Values.config.database.schema | quote }}
  SPRING_FLYWAY_SCHEMAS: {{ .Values.config.database.schema | quote }}
  SPRING_FLYWAY_DEFAULT_SCHEMA: {{ .Values.config.database.schema | quote }}
  SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE: {{ .Values.config.database.poolSize | quote }}
  SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE: {{ .Values.config.database.poolMinIdle | quote }}
  SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: {{ .Values.config.database.connTimeout | quote }}
  SPRING_JPA_HIBERNATE_DDL_AUTO: {{ .Values.config.jpa.ddlAuto | quote }}
  SPRING_JPA_SHOW_SQL: {{ .Values.config.jpa.showSql | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: {{ .Values.config.oauth2.issuerUri | quote }}
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: {{ .Values.config.oauth2.jwkSetUri | quote }}
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.config.kafka.bootstrapServers | quote }}
  SPRING_KAFKA_CONSUMER_GROUP_ID: {{ .Values.config.kafka.consumerGroup | quote }}
  SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET: {{ .Values.config.kafka.autoOffsetReset | quote }}
  KAFKA_TOPICS_JOIN_REQUEST_SENT: {{ .Values.config.kafka.topics.joinRequestSent | quote }}
  KAFKA_TOPICS_JOIN_REQUEST_RESPONDED: {{ .Values.config.kafka.topics.joinRequestResponded | quote }}
  KAFKA_TOPICS_INVITATION_SENT: {{ .Values.config.kafka.topics.invitationSent | quote }}
  KAFKA_TOPICS_INVITATION_RESPONDED: {{ .Values.config.kafka.topics.invitationResponded | quote }}
  KAFKA_TOPICS_EVENT_ATTENDANCE_ACCEPTED: {{ .Values.config.kafka.topics.eventAttendanceAccepted | quote }}
  SENDGRID_FROM_EMAIL: {{ .Values.config.sendgrid.fromEmail | quote }}
  SENDGRID_FROM_NAME: {{ .Values.config.sendgrid.fromName | quote }}
  USER_SERVICE_BASE_URL: {{ .Values.config.userService.baseUrl | quote }}
  USER_SERVICE_USER_ENDPOINT: {{ .Values.config.userService.userEndpoint | quote }}
  SPRING_FLYWAY_ENABLED: {{ .Values.config.flyway.enabled | quote }}
  SWAGGER_ENABLED: {{ .Values.config.swagger.enabled | quote }}
  SERVER_CONTEXT_PATH: {{ .Values.config.context.path | quote }}
  LOGGING_LEVEL_ROOT: {{ .Values.config.logging.levelRoot | quote }}
  LOGGING_LEVEL_COM_PLANIFY_NOTIFICATION: {{ .Values.config.logging.levelApp | quote }}
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: {{ .Values.config.logging.levelSpringWeb | quote }}
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: {{ .Values.config.logging.levelSpringSecurity | quote }}
  LOGGING_LEVEL_ORG_HIBERNATE_SQL: {{ .Values.config.logging.levelHibernateSql | quote }}