apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.database.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.database.password | quote }}
  # Optional integrations
  SENDGRID_API_KEY: {{ .Values.secrets.sendgrid.apiKey | quote }}
  TWILIO_ACCOUNT_SID: {{ .Values.secrets.twilio.accountSid | quote }}
  TWILIO_AUTH_TOKEN: {{ .Values.secrets.twilio.authToken | quote }}
  TWILIO_PHONE_NUMBER: {{ .Values.secrets.twilio.phoneNumber | quote }}