apiVersion: v1
kind: Secret
metadata:
  name: notification-service-secrets
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: {{ .Values.secrets.database.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.secrets.database.password | quote }}
  # Optional integrations
  SENDGRID_API_KEY: {{ .Values.secrets.sendgrid.apiKey | quote }}
  VONAGE_API_KEY: {{ .Values.secrets.vonage.apiKey | quote }}
  VONAGE_API_SECRET: {{ .Values.secrets.vonage.apiSecret | quote }}
  VONAGE_PHONE_NUMBER: {{ .Values.secrets.vonage.phoneNumber | quote }}