config:
  springProfilesActive: "dev"
  
  jpa:
    showSql: "true"
  
  kafka:
    autoOffsetReset: "earliest"
  
  swagger:
    enabled: "true"

  context:
    path: "/notification-service"
  
  logging:
    levelRoot: "INFO"
    levelApp: "DEBUG"
    levelSpringWeb: "INFO"
    levelSpringSecurity: "DEBUG"
    levelHibernateSql: "INFO"

replicaCount: 1

resources:
  requests:
    memory: "256Mi"
    cpu: "50m"
  limits:
    memory: "512Mi"
    cpu: "250m"

probes:
  liveness:
    initialDelaySeconds: 150
  readiness:
    initialDelaySeconds: 120