config:
  springProfilesActive: "prod"
  
  jpa:
    showSql: "false"
  
  kafka:
    autoOffsetReset: "latest"
  
  swagger:
    enabled: "false"

  context:
    path: "/notification-service"
  
  logging:
    levelRoot: "WARN"
    levelApp: "INFO"
    levelSpringWeb: "WARN"
    levelSpringSecurity: "WARN"
    levelHibernateSql: "WARN"